#TO create the 2 database run this commands:
# rails db:create
#This will create the database in postgresql and mysql
# & 
#rails db:migrate to push the table to the database

ware_house: &ware_house
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: roc_elv_db_warehouse
  username: 
  password: 
  host: localhost

mysql: &mysql
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: roc_elv_db
  username: root
  password: razakade123
  host: localhost

development:
  <<: *mysql
  <<: *ware_house

test:
  <<: *mysql
  <<: *ware_house

production:
  <<: *mysql
  <<: *ware_house

