mysql: &mysql
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: roc_elv_db
  username: root
  password: razakade123
  host: localhost

development:
  <<: *mysql

test:
  <<: *mysql


