ware_house: &ware_house
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: roc_elv_db_warehouse
  username: codeboxx
  password: Codeboxx1!
  host: codeboxx-postgresql.cq6zrczewpu2.us-east-1.rds.amazonaws.com

development:
  <<: *ware_house

test:
  <<: *ware_house
