ware_house: &ware_house
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: roc_elv_db_warehouse
  username: 
  password: 
  host: localhost

development:
  <<: *ware_house

test:
  <<: *ware_house
